version: '3.4'

# The environment variables are taken, by default, from the ".env" file defined like:
#     USER_SERVICE_USERNAME="blahblah"
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - registry-mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      # Beware of special characters in password that can be interpreted by shell
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=regdata
      - MYSQL_USER=reguser
      - MYSQL_PASSWORD=regpassword
    restart: always
    networks:
      - registry-network

  registry-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=regdata;Uid=reguser;Pwd=regpassword;
      - Database__DatabaseType=${DATABASE_TYPE}
      - UserServiceUsername=${USER_SERVICE_USERNAME}
      - UserServicePassword=${USER_SERVICE_PASSWORD}
    depends_on:
      - sqldata
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: 
      - /wait-for.sh
      - mysql:3306
      - -t
      - "120"
      - --
      - dotnet
      - Correspondence.dll
    networks:
      - registry-network
    ports:
      - "5102:80"

volumes:
  registry-mysqldata:
    external: false
    
networks:
  registry-network: