version: '3.4'

# The environment variables are taken, by default, from the ".env" file defined like:
#     USER_SERVICE_USERNAME="blahblah"
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - registry-sqldata:/var/opt/mssql
    networks:
      - registry-network

  registry-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sqldata;Database=${REGISTRY_DB};User Id=sa;Password=Pass@word
      - Database__DatabaseType=${DATABASE_TYPE}
      - UserServiceUsername=${USER_SERVICE_USERNAME}
      - UserServicePassword=${USER_SERVICE_PASSWORD}
    depends_on:
      - sqldata
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: 
      - /wait-for.sh
      - sqldata:1433
      - -t
      - "120"
      - --
      - dotnet
      - Correspondence.dll
    networks:
      - registry-network
    ports:
      - "5102:80"

volumes:
  registry-sqldata:
    external: false
    
networks:
  registry-network: